name: lake-tourism # You can rename this
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10  # Or whatever version you're using
  - netCDF4
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cmocean
  - ipympl
