name: genz-adcp-env  # You can rename this
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10  # Or whatever version you're using
  - numpy
  - pandas
  - matplotlib
  - ipympl
  - scipy
  - netcdf4
  - xarray
  - cmocean
  - bottleneck
  - plotly
  - scikit-learn
  - cartopy
  - pyyaml
  - gpxpy
  - python-dateutil
  - jupyter
  - notebook
  - ipython
  - ipywidgets
